# Generated by Django 4.2.3 on 2023-08-17 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='session_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ID da sessão'),
        ),
    ]
