# Generated by Django 4.2 on 2023-07-15 00:58

import apps.user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=20, unique=True, validators=[apps.user.models.validate_text], verbose_name='Nick'),
        ),
    ]
