# Generated by Django 4.2.3 on 2023-08-22 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_session_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(default='/home/luiggysilva/Documentos/CODING/django_projects/telezap_django/app/mediafiles/default_profile_photo.jpg', upload_to='user_profiles_photos', verbose_name='Foto'),
        ),
    ]
