# Generated by Django 4.2.3 on 2023-08-23 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_user_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='in_chat_or_groupchat',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Chat ou grupo atual'),
        ),
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, upload_to='user_profiles_photos', verbose_name='Foto'),
        ),
    ]
