# Generated by Django 4.2.3 on 2023-08-23 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_user_in_chat_or_groupchat_alter_user_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='in_chat_or_groupchat',
        ),
        migrations.AddField(
            model_name='user',
            name='in_chat',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ativo agora no(s) Chat(s)'),
        ),
        migrations.AddField(
            model_name='user',
            name='in_groupchat',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ativo agora no(s) Grupo(s)'),
        ),
    ]
