# Generated by Django 4.2.3 on 2023-08-24 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_remove_user_in_chat_or_groupchat_user_in_chat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='in_chat',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Ativo agora no(s) Chat(s)'),
        ),
        migrations.AlterField(
            model_name='user',
            name='in_groupchat',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Ativo agora no(s) Grupo(s)'),
        ),
    ]
