# Generated by Django 4.2.3 on 2023-08-09 02:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendshiprequest',
            name='notification_type',
            field=models.CharField(default='A', editable=False, max_length=1, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='grouprequest',
            name='group',
            field=models.IntegerField(verbose_name='Grupo'),
        ),
        migrations.AlterField(
            model_name='grouprequest',
            name='notification_type',
            field=models.CharField(default='G', editable=False, max_length=1, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='autores', to=settings.AUTH_USER_MODEL, verbose_name='Autor'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='author_view',
            field=models.BooleanField(default=True, verbose_name='Visualização do autor'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recebedores', to=settings.AUTH_USER_MODEL, verbose_name='Recebedor'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='receiver_view',
            field=models.BooleanField(default=True, verbose_name='Visualização do recebedor'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='status',
            field=models.CharField(choices=[('P', 'Pendente'), ('A', 'Aceito'), ('R', 'Recusado')], default=('P', 'Pendente'), max_length=1, verbose_name='Status'),
        ),
    ]
