# Generated by Django 4.2.3 on 2023-08-09 02:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0003_alter_chatmessage_unique_together_alter_chat_user1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='user1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user1_chats', to=settings.AUTH_USER_MODEL, verbose_name='Usuário 1'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='user1_view',
            field=models.BooleanField(default=True, verbose_name='Visualização do usuário 1'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='user2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user2_chats', to=settings.AUTH_USER_MODEL, verbose_name='Usuário 2'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='user2_view',
            field=models.BooleanField(default=True, verbose_name='Visualização do usuário 2'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.chat', verbose_name='Chat'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.message', verbose_name='Mensagem'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='visualized',
            field=models.BooleanField(default=False, verbose_name='Visualizada'),
        ),
        migrations.AlterField(
            model_name='imagemessage',
            name='image',
            field=models.ImageField(upload_to='user_chat_media', verbose_name='Imagem'),
        ),
        migrations.AlterField(
            model_name='message',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Autor'),
        ),
        migrations.AlterField(
            model_name='message',
            name='message_type',
            field=models.CharField(choices=[('T', 'Texto'), ('I', 'Imagem'), ('A', 'Audio'), ('V', 'Video')], editable=False, max_length=1, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='textmessage',
            name='text',
            field=models.TextField(verbose_name='Texto'),
        ),
        migrations.AlterUniqueTogether(
            name='chatmessage',
            unique_together={('chat', 'message')},
        ),
    ]
