# Generated by Django 4.2.3 on 2023-08-17 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_remove_chatmessage_date_message_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemessage',
            name='image',
            field=models.ImageField(upload_to='user_chat_media/images/', verbose_name='Imagem'),
        ),
    ]
