# Generated by Django 4.2.3 on 2023-09-08 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_alter_chat_options_alter_chat_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='user1_exit_chat_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de saída do usuário 1'),
        ),
        migrations.AddField(
            model_name='chat',
            name='user2_exit_chat_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de saída do usuário 2'),
        ),
    ]
